(function() {
  'use strict';

  window.registerArticle(
    '70-30-ai-rules',
    'content/posts/2025/70-30-ai-rules.md',
    '最佳实践：70% 现成 + 30% 手写',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'Ring-26-vs-Ling-26-蚂蚁集团双旗舰模型对比',
    'content/posts/2025/Ring-2.6-vs-Ling-2.6-蚂蚁集团双旗舰模型对比.md',
    'Ring-2.6-vs-Ling-2.6-蚂蚁集团双旗舰模型对比',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'andrej-karpathy-skills',
    'content/posts/2025/andrej-karpathy-skills.md',
    'andrej-karpathy-skills',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'awesome-design-md',
    'content/posts/2025/awesome-design-md.md',
    'awesome-design-md',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'chrome-devtools-mcp',
    'content/posts/2025/chrome-devtools-mcp.md',
    'AI agent 可以：',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'claude-code-router',
    'content/posts/2025/claude-code-router.md',
    'claude-code-router',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'demo-article',
    'content/posts/2025/demo-article.md',
    'Demo 文章',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'everything-claude-code',
    'content/posts/2025/everything-claude-code.md',
    '通过 npm 安装',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'fly-http-library',
    'content/posts/2025/fly-http-library.md',
    'fly-http-library',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'flyenv-dev-toolkit',
    'content/posts/2025/flyenv-dev-toolkit.md',
    'flyenv-dev-toolkit',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'gemini-cli-tool',
    'content/posts/2025/gemini-cli-tool.md',
    '或',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'github-tools-collection',
    'content/posts/2025/github-tools-collection.md',
    'github-tools-collection',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'medoo-php-orm',
    'content/posts/2025/medoo-php-orm.md',
    'medoo-php-orm',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'meta-prompt-strategy',
    'content/posts/2025/meta-prompt-strategy.md',
    '让 AI 来生成 AI 的规则和脚本：独狼开发者的元提示词策略',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'openharness-agent-platform',
    'content/posts/2025/openharness-agent-platform.md',
    'openharness-agent-platform',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'openrelay-free-ai-quota',
    'content/posts/2025/openrelay-free-ai-quota.md',
    '获取 API 密钥',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'poolside-ai-introduction',
    'content/posts/2025/poolside-ai-introduction.md',
    'poolside-ai-introduction',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'proxy-pool-scrapy',
    'content/posts/2025/proxy-pool-scrapy.md',
    '获取随机可用代理',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'qoder-qwen-relationship',
    'content/posts/2025/qoder-qwen-relationship.md',
    'qoder-qwen-relationship',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'ssh-mcp-server',
    'content/posts/2025/ssh-mcp-server.md',
    'ssh-mcp-server',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'vue-lazyload-plugin',
    'content/posts/2025/vue-lazyload-plugin.md',
    'vue-lazyload-plugin',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'vue-quill-editor-rich-text',
    'content/posts/2025/vue-quill-editor-rich-text.md',
    'vue-quill-editor-rich-text',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'wux-weapp-components',
    'content/posts/2025/wux-weapp-components.md',
    'wux-weapp-components',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'wxpy-wechat-bot',
    'content/posts/2025/wxpy-wechat-bot.md',
    'wxpy-wechat-bot',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'xlua-unity-hotfix',
    'content/posts/2025/xlua-unity-hotfix.md',
    'xlua-unity-hotfix',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    '蚂蚁集团-Ring-26-1T-万亿参数开源推理模型免费体验',
    'content/posts/2025/蚂蚁集团-Ring-2.6-1T-万亿参数开源推理模型免费体验.md',
    '蚂蚁集团 Ring-2.6-1T：万亿参数开源推理模型免费体验',
    '',
    '2025-05-01',
    'other'
  );
  window.registerArticle(
    'CMS打造既话0-1',
    'content/posts/AI/CMS打造既话0-1.md',
    'CMS打造既话0-1',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'ClaudeCode-约束claudecode',
    'content/posts/AI/ClaudeCode/约束claudecode.md',
    '约束claudecode',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'MCP-全局MCP',
    'content/posts/AI/MCP/全局MCP.md',
    '全局MCP',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'OpenCode-opencode同步配置命令',
    'content/posts/AI/OpenCode/opencode同步配置命令.md',
    'opencode同步配置命令',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'OpenCode-opencode我的配置文件',
    'content/posts/AI/OpenCode/opencode我的配置文件.md',
    'opencode我的配置文件',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'SKILLS-skill生成提示词',
    'content/posts/AI/SKILLS/skill生成提示词.md',
    '角色设定',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'SKILLS-skill触发例子',
    'content/posts/AI/SKILLS/skill触发例子.md',
    'skill触发例子',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'SKILLS-千问cli安装',
    'content/posts/AI/SKILLS/千问cli安装.md',
    '千问cli安装',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'SKILLS-千问提示词',
    'content/posts/AI/SKILLS/千问提示词.md',
    '千问提示词',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    '使用技巧',
    'content/posts/AI/使用技巧.md',
    '使用技巧',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    '搭建AI模型训练',
    'content/posts/AI/搭建AI模型训练.md',
    '搭建AI模型训练',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    '记忆沉淀专用提示词复制即用',
    'content/posts/AI/记忆沉淀专用提示词（复制即用）.md',
    '角色设定',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    '魔塔社区配置',
    'content/posts/AI/魔塔社区配置.md',
    '魔塔社区配置',
    '',
    '2025-05-01',
    'ai'
  );
  window.registerArticle(
    'Docker入门介绍',
    'content/posts/Docker/Docker入门介绍.md',
    'Docker入门介绍',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Docker指令',
    'content/posts/Docker/Docker指令.md',
    'Docker指令',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Docker镜像源配置',
    'content/posts/Docker/Docker镜像源配置.md',
    'Docker镜像源配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Hadoop-Docker搭建运行环境',
    'content/posts/Docker/Hadoop-Docker搭建运行环境.md',
    'Hadoop-Docker搭建运行环境',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Hadoop-Docker模拟环境账号',
    'content/posts/Docker/Hadoop-Docker模拟环境账号.md',
    'Hadoop-Docker模拟环境账号',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'NginxPHPMariaDBRedis环境搭建',
    'content/posts/Docker/Nginx+PHP+MariaDB+Redis环境搭建.md',
    'Nginx+PHP+MariaDB+Redis环境搭建',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Nginx基本配置',
    'content/posts/Docker/Nginx基本配置.md',
    'Nginx基本配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '容器与主机复制文件',
    'content/posts/Docker/容器与主机复制文件.md',
    '容器与主机复制文件',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Fork项目同步上游更新',
    'content/posts/Git/Fork项目同步上游更新.md',
    'Fork项目同步上游更新',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Fork项目选择性更新',
    'content/posts/Git/Fork项目选择性更新.md',
    'Fork项目选择性更新',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Gitee私有仓库部署DeployKey',
    'content/posts/Git/Gitee私有仓库部署DeployKey.md',
    'Gitee私有仓库部署DeployKey',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Git分支管理',
    'content/posts/Git/Git分支管理.md',
    'Git分支管理',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Git基本操作入门',
    'content/posts/Git/Git基本操作入门.md',
    'Git基本操作入门',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Git常用操作',
    'content/posts/Git/Git常用操作.md',
    'Git常用操作',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    'Git远程仓库',
    'content/posts/Git/Git远程仓库.md',
    'Git远程仓库',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    '关于FORK合并原项目',
    'content/posts/Git/关于FORK合并原项目.md',
    '关于FORK合并原项目',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    '创建多个SSHKey',
    'content/posts/Git/创建多个SSHKey.md',
    '创建多个SSHKey',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    '合并分支指定内容',
    'content/posts/Git/合并分支指定内容.md',
    '合并分支指定内容',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    '清理git缓存减小仓库大小',
    'content/posts/Git/清理git缓存减小仓库大小.md',
    '清理git缓存减小仓库大小',
    '',
    '2025-05-01',
    'git'
  );
  window.registerArticle(
    '500错误跳转404隐藏报错',
    'content/posts/PHP/500错误跳转404隐藏报错.md',
    '500错误跳转404隐藏报错',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'OPcache配置指南',
    'content/posts/PHP/OPcache配置指南.md',
    'PHP OPcache 配置指南',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-Phinx',
    'content/posts/PHP/Phinx/Phinx.md',
    'Phinx',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-Up-Down-Change场景',
    'content/posts/PHP/Phinx/Up-Down-Change场景.md',
    'Up-Down-Change场景',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-新增表',
    'content/posts/PHP/Phinx/新增表.md',
    '新增表',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-更新数据',
    'content/posts/PHP/Phinx/更新数据.md',
    '更新数据',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-添加字段',
    'content/posts/PHP/Phinx/添加字段.md',
    '添加字段',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Phinx-添加数据',
    'content/posts/PHP/Phinx/添加数据.md',
    '添加数据',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Sitemap写入权限问题排查',
    'content/posts/PHP/Sitemap写入权限问题排查.md',
    'Sitemap写入权限问题排查',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'ThinkPHP-连接SQLServer',
    'content/posts/PHP/ThinkPHP/连接SQLServer.md',
    '连接SQLServer',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Wordpress-使用手册',
    'content/posts/PHP/Wordpress/使用手册.md',
    '使用手册',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '网站路由解决方案',
    'content/posts/PHP/网站路由解决方案.md',
    '网站路由解决方案',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '设置文件上传大小限制',
    'content/posts/PHP/设置文件上传大小限制.md',
    '设置文件上传大小限制',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Cloudflare全站缓存配置流程',
    'content/posts/cloudflare/Cloudflare全站缓存配置流程.md',
    'Cloudflare全站缓存配置流程',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Cloudflare负载均衡配置实战文档解决Critical报错',
    'content/posts/cloudflare/Cloudflare负载均衡配置实战文档（解决Critical报错）.md',
    'Cloudflare负载均衡配置实战文档（解决Critical报错）',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '清除CSS缓存',
    'content/posts/cloudflare/清除CSS缓存.md',
    '清除CSS缓存',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '配置DNS访问及SSL',
    'content/posts/cloudflare/配置DNS访问及SSL.md',
    '配置DNS访问及SSL',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'vim指令',
    'content/posts/linux/vim指令.md',
    'vim指令',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '定时器',
    'content/posts/linux/定时器.md',
    '定时器',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '定时备份数据库',
    'content/posts/linux/定时备份数据库.md',
    '定时备份数据库',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '常用指令',
    'content/posts/linux/常用指令.md',
    '常用指令',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '批量删除find结果文件',
    'content/posts/linux/批量删除find结果文件.md',
    '批量删除find结果文件',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '批量权限设置',
    'content/posts/linux/批量权限设置.md',
    '批量权限设置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '挂载云盘',
    'content/posts/linux/挂载云盘.md',
    '挂载云盘',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '服务器之间互传文件',
    'content/posts/linux/服务器之间互传文件.md',
    '服务器之间互传文件',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '清理多项目下的缓存',
    'content/posts/linux/清理多项目下的缓存.md',
    '清理多项目下的缓存',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '统计网站访问流量',
    'content/posts/linux/统计网站访问流量.md',
    '统计网站访问流量',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Clash-Verge本地域名直连配置',
    'content/posts/mac/Clash-Verge本地域名直连配置.md',
    'Clash-Verge本地域名直连配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Homebrew安装与配置',
    'content/posts/mac/Homebrew安装与配置.md',
    'Homebrew安装与配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'MacPorts包管理工具',
    'content/posts/mac/MacPorts包管理工具.md',
    'MacPorts包管理工具',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'MacPorts安装PHP8',
    'content/posts/mac/MacPorts安装PHP8.md',
    'MacPorts安装PHP8',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'iTerm2配置多服务器连接',
    'content/posts/mac/iTerm2配置多服务器连接.md',
    'iTerm2配置多服务器连接',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'mac本地ThinkPHPFileNotFound修复',
    'content/posts/mac/mac本地ThinkPHPFileNotFound修复.md',
    'mac本地ThinkPHPFileNotFound修复',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'mac本地静态页404403修复',
    'content/posts/mac/mac本地静态页404403修复.md',
    'mac本地静态页404403修复',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '微信多开',
    'content/posts/mac/微信多开.md',
    '微信多开',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '本地MySQL密码',
    'content/posts/mac/本地MySQL密码.md',
    '本地MySQL密码',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'SQL替换字段内容',
    'content/posts/mysql/SQL替换字段内容.md',
    'SQL替换字段内容',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '关系除法查找满足所有条件的记录',
    'content/posts/mysql/关系除法查找满足所有条件的记录.md',
    '关系除法查找满足所有条件的记录',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '定义变量',
    'content/posts/mysql/定义变量.md',
    'MySQL 变量定义与使用',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '数据库授权',
    'content/posts/mysql/数据库授权.md',
    '数据库授权',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    '查询所有表是否存在某字段',
    'content/posts/mysql/查询所有表是否存在某字段.md',
    '查询所有表是否存在某字段',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'Nginx正式上线配置模板',
    'content/posts/nginx/Nginx正式上线配置模板.md',
    'Nginx正式上线配置模板',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Nginx跨平台静态资源配置',
    'content/posts/nginx/Nginx跨平台静态资源配置.md',
    'Nginx跨平台静态资源配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Nginx配置优化',
    'content/posts/nginx/Nginx配置优化.md',
    'Nginx 配置优化指南',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'OpenResty与Nginx对比',
    'content/posts/nginx/OpenResty与Nginx对比.md',
    'OpenResty',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'PHP标准配置文件',
    'content/posts/nginx/PHP标准配置文件.md',
    'PHP标准配置文件',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Phinx的8088端口配置',
    'content/posts/nginx/Phinx的8088端口配置.md',
    'Phinx的8088端口配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'Swoole反向代理配置',
    'content/posts/nginx/Swoole反向代理配置.md',
    'Swoole反向代理配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'gzip配置',
    'content/posts/nginx/gzip配置.md',
    'gzip配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '伪静态模板',
    'content/posts/nginx/伪静态模板.md',
    '伪静态模板',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '关闭站点配置',
    'content/posts/nginx/关闭站点配置.md',
    '关闭站点配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '大小写路径处理',
    'content/posts/nginx/大小写路径处理.md',
    '大小写路径处理',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '非WWW跳转WWW',
    'content/posts/nginx/非WWW跳转WWW.md',
    '非WWW跳转WWW',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'pymysql',
    'content/posts/python/pymysql.md',
    'pymysql',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'python虚拟环境',
    'content/posts/python/python虚拟环境.md',
    'python虚拟环境',
    '',
    '2025-05-01',
    'backend'
  );
  window.registerArticle(
    'A标签Lighthouse爬取链接修复',
    'content/posts/web/A标签Lighthouse爬取链接修复.md',
    'A标签Lighthouse爬取链接修复',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'ueditor编辑器修复',
    'content/posts/web/ueditor编辑器修复.md',
    'ueditor编辑器修复',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    '外贸独立站产品筛选同步与异步方案',
    'content/posts/web/外贸独立站产品筛选同步与异步方案.md',
    '外贸独立站产品筛选同步与异步方案',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'CSS-左图右文点击切换',
    'content/posts/前端/CSS/左图右文点击切换.md',
    '左图右文点击切换',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'CSS-文字纵向显示',
    'content/posts/前端/CSS/文字纵向显示.md',
    '文字纵向显示',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'CSS-自定义输入下拉框',
    'content/posts/前端/CSS/自定义输入下拉框.md',
    '自定义输入下拉框',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'CSS片段汇总',
    'content/posts/前端/CSS片段汇总.md',
    'CSS 片段汇总',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'JS-form表单提交验证',
    'content/posts/前端/JS/form表单提交验证.md',
    'form表单提交验证',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    'JS片段汇总',
    'content/posts/前端/JS片段汇总.md',
    'JS 片段汇总',
    '',
    '2025-05-01',
    'frontend'
  );
  window.registerArticle(
    '1PanelCloudflare企業官網HTTPS證書配置實戰指南',
    'content/posts/服务器/1Panel+Cloudflare企業官網HTTPS證書配置實戰指南.md',
    '1Panel+Cloudflare企業官網HTTPS證書配置實戰指南',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    'cloudflareCDN域名配置',
    'content/posts/服务器/cloudflareCDN域名配置.md',
    'cloudflareCDN域名配置',
    '',
    '2025-05-01',
    'devops'
  );
  window.registerArticle(
    '服务器0到1搭建',
    'content/posts/服务器/服务器0到1搭建.md',
    '服务器0到1搭建',
    '',
    '2025-05-01',
    'devops'
  );

})();
